CREATE TABLE zeitzonen (
  id INT AUTO_INCREMENT PRIMARY KEY,
  zeitzone VARCHAR(100) NOT NULL,
  stadt VARCHAR(100) NOT NULL,
  cover VARCHAR(100) NOT NULL
);

INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (1, 'Africa/Abidjan', 'Abidjan', 'Abidjan.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (2, 'Africa/Accra', 'Accra', 'Accra.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (3, 'Africa/Addis_Ababa', 'Addis Ababa', 'Addis Ababa.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (4, 'Africa/Algiers', 'Algiers', 'Algiers.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (5, 'Africa/Asmara', 'Asmara', 'Asmara.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (6, 'Africa/Asmera', 'Asmera', 'Asmera.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (7, 'Africa/Bamako', 'Bamako', 'Bamako.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (8, 'Africa/Bangui', 'Bangui', 'Bangui.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (9, 'Africa/Banjul', 'Banjul', 'Banjul.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (10, 'Africa/Bissau', 'Bissau', 'Bissau.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (11, 'Africa/Blantyre', 'Blantyre', 'Blantyre.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (12, 'Africa/Brazzaville', 'Brazzaville', 'Brazzaville.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (13, 'Africa/Bujumbura', 'Bujumbura', 'Bujumbura.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (14, 'Africa/Cairo', 'Cairo', 'Cairo.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (15, 'Africa/Casablanca', 'Casablanca', 'Casablanca.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (16, 'Africa/Ceuta', 'Ceuta', 'Ceuta.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (17, 'Africa/Conakry', 'Conakry', 'Conakry.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (18, 'Africa/Dakar', 'Dakar', 'Dakar.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (19, 'Africa/Dar_es_Salaam', 'Dar Es Salaam', 'Dar Es Salaam.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (20, 'Africa/Djibouti', 'Djibouti', 'Djibouti.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (21, 'Africa/Douala', 'Douala', 'Douala.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (22, 'Africa/El_Aaiun', 'El Aaiun', 'El Aaiun.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (23, 'Africa/Freetown', 'Freetown', 'Freetown.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (24, 'Africa/Gaborone', 'Gaborone', 'Gaborone.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (25, 'Africa/Harare', 'Harare', 'Harare.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (26, 'Africa/Johannesburg', 'Johannesburg', 'Johannesburg.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (27, 'Africa/Juba', 'Juba', 'Juba.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (28, 'Africa/Kampala', 'Kampala', 'Kampala.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (29, 'Africa/Khartoum', 'Khartoum', 'Khartoum.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (30, 'Africa/Kigali', 'Kigali', 'Kigali.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (31, 'Africa/Kinshasa', 'Kinshasa', 'Kinshasa.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (32, 'Africa/Lagos', 'Lagos', 'Lagos.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (33, 'Africa/Libreville', 'Libreville', 'Libreville.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (34, 'Africa/Lome', 'Lome', 'Lome.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (35, 'Africa/Luanda', 'Luanda', 'Luanda.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (36, 'Africa/Lubumbashi', 'Lubumbashi', 'Lubumbashi.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (37, 'Africa/Lusaka', 'Lusaka', 'Lusaka.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (38, 'Africa/Malabo', 'Malabo', 'Malabo.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (39, 'Africa/Maputo', 'Maputo', 'Maputo.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (40, 'Africa/Maseru', 'Maseru', 'Maseru.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (41, 'Africa/Mbabane', 'Mbabane', 'Mbabane.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (42, 'Africa/Mogadishu', 'Mogadishu', 'Mogadishu.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (43, 'Africa/Monrovia', 'Monrovia', 'Monrovia.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (44, 'Africa/Nairobi', 'Nairobi', 'Nairobi.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (45, 'Africa/Ndjamena', 'Ndjamena', 'Ndjamena.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (46, 'Africa/Niamey', 'Niamey', 'Niamey.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (47, 'Africa/Nouakchott', 'Nouakchott', 'Nouakchott.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (48, 'Africa/Ouagadougou', 'Ouagadougou', 'Ouagadougou.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (49, 'Africa/Porto-Novo', 'Porto-Novo', 'Porto-Novo.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (50, 'Africa/Sao_Tome', 'Sao Tome', 'Sao Tome.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (51, 'Africa/Timbuktu', 'Timbuktu', 'Timbuktu.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (52, 'Africa/Tripoli', 'Tripoli', 'Tripoli.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (53, 'Africa/Tunis', 'Tunis', 'Tunis.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (54, 'Africa/Windhoek', 'Windhoek', 'Windhoek.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (55, 'America/Adak', 'Adak', 'Adak.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (56, 'America/Anchorage', 'Anchorage', 'Anchorage.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (57, 'America/Anguilla', 'Anguilla', 'Anguilla.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (58, 'America/Antigua', 'Antigua', 'Antigua.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (59, 'America/Araguaina', 'Araguaina', 'Araguaina.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (60, 'America/Argentina/Buenos_Aires', 'Buenos Aires', 'Buenos Aires.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (61, 'America/Argentina/Catamarca', 'Catamarca', 'Catamarca.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (62, 'America/Argentina/ComodRivadavia', 'Comodrivadavia', 'Comodrivadavia.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (63, 'America/Argentina/Cordoba', 'Cordoba', 'Cordoba.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (64, 'America/Argentina/Jujuy', 'Jujuy', 'Jujuy.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (65, 'America/Argentina/La_Rioja', 'La Rioja', 'La Rioja.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (66, 'America/Argentina/Mendoza', 'Mendoza', 'Mendoza.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (67, 'America/Argentina/Rio_Gallegos', 'Rio Gallegos', 'Rio Gallegos.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (68, 'America/Argentina/Salta', 'Salta', 'Salta.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (69, 'America/Argentina/San_Juan', 'San Juan', 'San Juan.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (70, 'America/Argentina/San_Luis', 'San Luis', 'San Luis.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (71, 'America/Argentina/Tucuman', 'Tucuman', 'Tucuman.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (72, 'America/Argentina/Ushuaia', 'Ushuaia', 'Ushuaia.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (73, 'America/Aruba', 'Aruba', 'Aruba.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (74, 'America/Asuncion', 'Asuncion', 'Asuncion.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (75, 'America/Atikokan', 'Atikokan', 'Atikokan.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (76, 'America/Atka', 'Atka', 'Atka.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (77, 'America/Bahia', 'Bahia', 'Bahia.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (78, 'America/Bahia_Banderas', 'Bahia Banderas', 'Bahia Banderas.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (79, 'America/Barbados', 'Barbados', 'Barbados.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (80, 'America/Belem', 'Belem', 'Belem.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (81, 'America/Belize', 'Belize', 'Belize.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (82, 'America/Blanc-Sablon', 'Blanc-Sablon', 'Blanc-Sablon.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (83, 'America/Boa_Vista', 'Boa Vista', 'Boa Vista.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (84, 'America/Bogota', 'Bogota', 'Bogota.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (85, 'America/Boise', 'Boise', 'Boise.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (86, 'America/Buenos_Aires', 'Buenos Aires', 'Buenos Aires.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (87, 'America/Cambridge_Bay', 'Cambridge Bay', 'Cambridge Bay.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (88, 'America/Campo_Grande', 'Campo Grande', 'Campo Grande.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (89, 'America/Cancun', 'Cancun', 'Cancun.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (90, 'America/Caracas', 'Caracas', 'Caracas.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (91, 'America/Catamarca', 'Catamarca', 'Catamarca.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (92, 'America/Cayenne', 'Cayenne', 'Cayenne.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (93, 'America/Cayman', 'Cayman', 'Cayman.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (94, 'America/Chicago', 'Chicago', 'Chicago.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (95, 'America/Chihuahua', 'Chihuahua', 'Chihuahua.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (96, 'America/Ciudad_Juarez', 'Ciudad Juarez', 'Ciudad Juarez.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (97, 'America/Coral_Harbour', 'Coral Harbour', 'Coral Harbour.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (98, 'America/Cordoba', 'Cordoba', 'Cordoba.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (99, 'America/Costa_Rica', 'Costa Rica', 'Costa Rica.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (100, 'America/Creston', 'Creston', 'Creston.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (101, 'America/Cuiaba', 'Cuiaba', 'Cuiaba.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (102, 'America/Curacao', 'Curacao', 'Curacao.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (103, 'America/Danmarkshavn', 'Danmarkshavn', 'Danmarkshavn.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (104, 'America/Dawson', 'Dawson', 'Dawson.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (105, 'America/Dawson_Creek', 'Dawson Creek', 'Dawson Creek.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (106, 'America/Denver', 'Denver', 'Denver.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (107, 'America/Detroit', 'Detroit', 'Detroit.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (108, 'America/Dominica', 'Dominica', 'Dominica.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (109, 'America/Edmonton', 'Edmonton', 'Edmonton.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (110, 'America/Eirunepe', 'Eirunepe', 'Eirunepe.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (111, 'America/El_Salvador', 'El Salvador', 'El Salvador.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (112, 'America/Ensenada', 'Ensenada', 'Ensenada.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (113, 'America/Fort_Nelson', 'Fort Nelson', 'Fort Nelson.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (114, 'America/Fort_Wayne', 'Fort Wayne', 'Fort Wayne.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (115, 'America/Fortaleza', 'Fortaleza', 'Fortaleza.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (116, 'America/Glace_Bay', 'Glace Bay', 'Glace Bay.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (117, 'America/Godthab', 'Godthab', 'Godthab.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (118, 'America/Goose_Bay', 'Goose Bay', 'Goose Bay.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (119, 'America/Grand_Turk', 'Grand Turk', 'Grand Turk.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (120, 'America/Grenada', 'Grenada', 'Grenada.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (121, 'America/Guadeloupe', 'Guadeloupe', 'Guadeloupe.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (122, 'America/Guatemala', 'Guatemala', 'Guatemala.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (123, 'America/Guayaquil', 'Guayaquil', 'Guayaquil.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (124, 'America/Guyana', 'Guyana', 'Guyana.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (125, 'America/Halifax', 'Halifax', 'Halifax.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (126, 'America/Havana', 'Havana', 'Havana.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (127, 'America/Hermosillo', 'Hermosillo', 'Hermosillo.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (128, 'America/Indiana/Indianapolis', 'Indianapolis', 'Indianapolis.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (129, 'America/Indiana/Knox', 'Knox', 'Knox.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (130, 'America/Indiana/Marengo', 'Marengo', 'Marengo.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (131, 'America/Indiana/Petersburg', 'Petersburg', 'Petersburg.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (132, 'America/Indiana/Tell_City', 'Tell City', 'Tell City.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (133, 'America/Indiana/Vevay', 'Vevay', 'Vevay.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (134, 'America/Indiana/Vincennes', 'Vincennes', 'Vincennes.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (135, 'America/Indiana/Winamac', 'Winamac', 'Winamac.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (136, 'America/Indianapolis', 'Indianapolis', 'Indianapolis.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (137, 'America/Inuvik', 'Inuvik', 'Inuvik.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (138, 'America/Iqaluit', 'Iqaluit', 'Iqaluit.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (139, 'America/Jamaica', 'Jamaica', 'Jamaica.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (140, 'America/Jujuy', 'Jujuy', 'Jujuy.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (141, 'America/Juneau', 'Juneau', 'Juneau.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (142, 'America/Kentucky/Louisville', 'Louisville', 'Louisville.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (143, 'America/Kentucky/Monticello', 'Monticello', 'Monticello.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (144, 'America/Knox_IN', 'Knox In', 'Knox In.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (145, 'America/Kralendijk', 'Kralendijk', 'Kralendijk.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (146, 'America/La_Paz', 'La Paz', 'La Paz.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (147, 'America/Lima', 'Lima', 'Lima.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (148, 'America/Los_Angeles', 'Los Angeles', 'Los Angeles.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (149, 'America/Louisville', 'Louisville', 'Louisville.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (150, 'America/Lower_Princes', 'Lower Princes', 'Lower Princes.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (151, 'America/Maceio', 'Maceio', 'Maceio.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (152, 'America/Managua', 'Managua', 'Managua.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (153, 'America/Manaus', 'Manaus', 'Manaus.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (154, 'America/Marigot', 'Marigot', 'Marigot.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (155, 'America/Martinique', 'Martinique', 'Martinique.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (156, 'America/Matamoros', 'Matamoros', 'Matamoros.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (157, 'America/Mazatlan', 'Mazatlan', 'Mazatlan.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (158, 'America/Mendoza', 'Mendoza', 'Mendoza.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (159, 'America/Menominee', 'Menominee', 'Menominee.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (160, 'America/Merida', 'Merida', 'Merida.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (161, 'America/Metlakatla', 'Metlakatla', 'Metlakatla.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (162, 'America/Mexico_City', 'Mexico City', 'Mexico City.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (163, 'America/Miquelon', 'Miquelon', 'Miquelon.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (164, 'America/Moncton', 'Moncton', 'Moncton.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (165, 'America/Monterrey', 'Monterrey', 'Monterrey.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (166, 'America/Montevideo', 'Montevideo', 'Montevideo.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (167, 'America/Montreal', 'Montreal', 'Montreal.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (168, 'America/Montserrat', 'Montserrat', 'Montserrat.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (169, 'America/Nassau', 'Nassau', 'Nassau.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (170, 'America/New_York', 'New York', 'New York.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (171, 'America/Nipigon', 'Nipigon', 'Nipigon.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (172, 'America/Nome', 'Nome', 'Nome.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (173, 'America/Noronha', 'Noronha', 'Noronha.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (174, 'America/North_Dakota/Beulah', 'Beulah', 'Beulah.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (175, 'America/North_Dakota/Center', 'Center', 'Center.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (176, 'America/North_Dakota/New_Salem', 'New Salem', 'New Salem.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (177, 'America/Nuuk', 'Nuuk', 'Nuuk.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (178, 'America/Ojinaga', 'Ojinaga', 'Ojinaga.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (179, 'America/Panama', 'Panama', 'Panama.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (180, 'America/Pangnirtung', 'Pangnirtung', 'Pangnirtung.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (181, 'America/Paramaribo', 'Paramaribo', 'Paramaribo.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (182, 'America/Phoenix', 'Phoenix', 'Phoenix.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (183, 'America/Port-au-Prince', 'Port-Au-Prince', 'Port-Au-Prince.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (184, 'America/Port_of_Spain', 'Port Of Spain', 'Port Of Spain.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (185, 'America/Porto_Acre', 'Porto Acre', 'Porto Acre.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (186, 'America/Porto_Velho', 'Porto Velho', 'Porto Velho.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (187, 'America/Puerto_Rico', 'Puerto Rico', 'Puerto Rico.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (188, 'America/Punta_Arenas', 'Punta Arenas', 'Punta Arenas.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (189, 'America/Rainy_River', 'Rainy River', 'Rainy River.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (190, 'America/Rankin_Inlet', 'Rankin Inlet', 'Rankin Inlet.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (191, 'America/Recife', 'Recife', 'Recife.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (192, 'America/Regina', 'Regina', 'Regina.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (193, 'America/Resolute', 'Resolute', 'Resolute.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (194, 'America/Rio_Branco', 'Rio Branco', 'Rio Branco.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (195, 'America/Rosario', 'Rosario', 'Rosario.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (196, 'America/Santa_Isabel', 'Santa Isabel', 'Santa Isabel.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (197, 'America/Santarem', 'Santarem', 'Santarem.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (198, 'America/Santiago', 'Santiago', 'Santiago.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (199, 'America/Santo_Domingo', 'Santo Domingo', 'Santo Domingo.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (200, 'America/Sao_Paulo', 'Sao Paulo', 'Sao Paulo.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (201, 'America/Scoresbysund', 'Scoresbysund', 'Scoresbysund.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (202, 'America/Shiprock', 'Shiprock', 'Shiprock.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (203, 'America/Sitka', 'Sitka', 'Sitka.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (204, 'America/St_Barthelemy', 'St Barthelemy', 'St Barthelemy.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (205, 'America/St_Johns', 'St Johns', 'St Johns.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (206, 'America/St_Kitts', 'St Kitts', 'St Kitts.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (207, 'America/St_Lucia', 'St Lucia', 'St Lucia.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (208, 'America/St_Thomas', 'St Thomas', 'St Thomas.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (209, 'America/St_Vincent', 'St Vincent', 'St Vincent.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (210, 'America/Swift_Current', 'Swift Current', 'Swift Current.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (211, 'America/Tegucigalpa', 'Tegucigalpa', 'Tegucigalpa.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (212, 'America/Thule', 'Thule', 'Thule.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (213, 'America/Thunder_Bay', 'Thunder Bay', 'Thunder Bay.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (214, 'America/Tijuana', 'Tijuana', 'Tijuana.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (215, 'America/Toronto', 'Toronto', 'Toronto.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (216, 'America/Tortola', 'Tortola', 'Tortola.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (217, 'America/Vancouver', 'Vancouver', 'Vancouver.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (218, 'America/Virgin', 'Virgin', 'Virgin.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (219, 'America/Whitehorse', 'Whitehorse', 'Whitehorse.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (220, 'America/Winnipeg', 'Winnipeg', 'Winnipeg.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (221, 'America/Yakutat', 'Yakutat', 'Yakutat.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (222, 'America/Yellowknife', 'Yellowknife', 'Yellowknife.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (223, 'Antarctica/Casey', 'Casey', 'Casey.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (224, 'Antarctica/Davis', 'Davis', 'Davis.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (225, 'Antarctica/DumontDUrville', 'Dumontdurville', 'Dumontdurville.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (226, 'Antarctica/Macquarie', 'Macquarie', 'Macquarie.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (227, 'Antarctica/Mawson', 'Mawson', 'Mawson.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (228, 'Antarctica/McMurdo', 'Mcmurdo', 'Mcmurdo.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (229, 'Antarctica/Palmer', 'Palmer', 'Palmer.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (230, 'Antarctica/Rothera', 'Rothera', 'Rothera.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (231, 'Antarctica/South_Pole', 'South Pole', 'South Pole.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (232, 'Antarctica/Syowa', 'Syowa', 'Syowa.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (233, 'Antarctica/Troll', 'Troll', 'Troll.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (234, 'Antarctica/Vostok', 'Vostok', 'Vostok.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (235, 'Arctic/Longyearbyen', 'Longyearbyen', 'Longyearbyen.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (236, 'Asia/Aden', 'Aden', 'Aden.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (237, 'Asia/Almaty', 'Almaty', 'Almaty.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (238, 'Asia/Amman', 'Amman', 'Amman.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (239, 'Asia/Anadyr', 'Anadyr', 'Anadyr.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (240, 'Asia/Aqtau', 'Aqtau', 'Aqtau.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (241, 'Asia/Aqtobe', 'Aqtobe', 'Aqtobe.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (242, 'Asia/Ashgabat', 'Ashgabat', 'Ashgabat.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (243, 'Asia/Ashkhabad', 'Ashkhabad', 'Ashkhabad.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (244, 'Asia/Atyrau', 'Atyrau', 'Atyrau.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (245, 'Asia/Baghdad', 'Baghdad', 'Baghdad.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (246, 'Asia/Bahrain', 'Bahrain', 'Bahrain.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (247, 'Asia/Baku', 'Baku', 'Baku.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (248, 'Asia/Bangkok', 'Bangkok', 'Bangkok.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (249, 'Asia/Barnaul', 'Barnaul', 'Barnaul.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (250, 'Asia/Beirut', 'Beirut', 'Beirut.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (251, 'Asia/Bishkek', 'Bishkek', 'Bishkek.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (252, 'Asia/Brunei', 'Brunei', 'Brunei.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (253, 'Asia/Calcutta', 'Calcutta', 'Calcutta.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (254, 'Asia/Chita', 'Chita', 'Chita.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (255, 'Asia/Choibalsan', 'Choibalsan', 'Choibalsan.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (256, 'Asia/Chongqing', 'Chongqing', 'Chongqing.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (257, 'Asia/Chungking', 'Chungking', 'Chungking.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (258, 'Asia/Colombo', 'Colombo', 'Colombo.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (259, 'Asia/Dacca', 'Dacca', 'Dacca.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (260, 'Asia/Damascus', 'Damascus', 'Damascus.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (261, 'Asia/Dhaka', 'Dhaka', 'Dhaka.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (262, 'Asia/Dili', 'Dili', 'Dili.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (263, 'Asia/Dubai', 'Dubai', 'Dubai.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (264, 'Asia/Dushanbe', 'Dushanbe', 'Dushanbe.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (265, 'Asia/Famagusta', 'Famagusta', 'Famagusta.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (266, 'Asia/Gaza', 'Gaza', 'Gaza.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (267, 'Asia/Harbin', 'Harbin', 'Harbin.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (268, 'Asia/Hebron', 'Hebron', 'Hebron.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (269, 'Asia/Ho_Chi_Minh', 'Ho Chi Minh', 'Ho Chi Minh.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (270, 'Asia/Hong_Kong', 'Hong Kong', 'Hong Kong.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (271, 'Asia/Hovd', 'Hovd', 'Hovd.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (272, 'Asia/Irkutsk', 'Irkutsk', 'Irkutsk.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (273, 'Asia/Istanbul', 'Istanbul', 'Istanbul.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (274, 'Asia/Jakarta', 'Jakarta', 'Jakarta.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (275, 'Asia/Jayapura', 'Jayapura', 'Jayapura.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (276, 'Asia/Jerusalem', 'Jerusalem', 'Jerusalem.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (277, 'Asia/Kabul', 'Kabul', 'Kabul.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (278, 'Asia/Kamchatka', 'Kamchatka', 'Kamchatka.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (279, 'Asia/Karachi', 'Karachi', 'Karachi.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (280, 'Asia/Kashgar', 'Kashgar', 'Kashgar.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (281, 'Asia/Kathmandu', 'Kathmandu', 'Kathmandu.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (282, 'Asia/Katmandu', 'Katmandu', 'Katmandu.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (283, 'Asia/Khandyga', 'Khandyga', 'Khandyga.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (284, 'Asia/Kolkata', 'Kolkata', 'Kolkata.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (285, 'Asia/Krasnoyarsk', 'Krasnoyarsk', 'Krasnoyarsk.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (286, 'Asia/Kuala_Lumpur', 'Kuala Lumpur', 'Kuala Lumpur.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (287, 'Asia/Kuching', 'Kuching', 'Kuching.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (288, 'Asia/Kuwait', 'Kuwait', 'Kuwait.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (289, 'Asia/Macao', 'Macao', 'Macao.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (290, 'Asia/Macau', 'Macau', 'Macau.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (291, 'Asia/Magadan', 'Magadan', 'Magadan.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (292, 'Asia/Makassar', 'Makassar', 'Makassar.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (293, 'Asia/Manila', 'Manila', 'Manila.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (294, 'Asia/Muscat', 'Muscat', 'Muscat.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (295, 'Asia/Nicosia', 'Nicosia', 'Nicosia.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (296, 'Asia/Novokuznetsk', 'Novokuznetsk', 'Novokuznetsk.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (297, 'Asia/Novosibirsk', 'Novosibirsk', 'Novosibirsk.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (298, 'Asia/Omsk', 'Omsk', 'Omsk.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (299, 'Asia/Oral', 'Oral', 'Oral.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (300, 'Asia/Phnom_Penh', 'Phnom Penh', 'Phnom Penh.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (301, 'Asia/Pontianak', 'Pontianak', 'Pontianak.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (302, 'Asia/Pyongyang', 'Pyongyang', 'Pyongyang.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (303, 'Asia/Qatar', 'Qatar', 'Qatar.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (304, 'Asia/Qostanay', 'Qostanay', 'Qostanay.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (305, 'Asia/Qyzylorda', 'Qyzylorda', 'Qyzylorda.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (306, 'Asia/Rangoon', 'Rangoon', 'Rangoon.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (307, 'Asia/Riyadh', 'Riyadh', 'Riyadh.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (308, 'Asia/Saigon', 'Saigon', 'Saigon.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (309, 'Asia/Sakhalin', 'Sakhalin', 'Sakhalin.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (310, 'Asia/Samarkand', 'Samarkand', 'Samarkand.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (311, 'Asia/Seoul', 'Seoul', 'Seoul.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (312, 'Asia/Shanghai', 'Shanghai', 'Shanghai.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (313, 'Asia/Singapore', 'Singapore', 'Singapore.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (314, 'Asia/Srednekolymsk', 'Srednekolymsk', 'Srednekolymsk.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (315, 'Asia/Taipei', 'Taipei', 'Taipei.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (316, 'Asia/Tashkent', 'Tashkent', 'Tashkent.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (317, 'Asia/Tbilisi', 'Tbilisi', 'Tbilisi.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (318, 'Asia/Tehran', 'Tehran', 'Tehran.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (319, 'Asia/Tel_Aviv', 'Tel Aviv', 'Tel Aviv.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (320, 'Asia/Thimbu', 'Thimbu', 'Thimbu.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (321, 'Asia/Thimphu', 'Thimphu', 'Thimphu.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (322, 'Asia/Tokyo', 'Tokyo', 'Tokyo.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (323, 'Asia/Tomsk', 'Tomsk', 'Tomsk.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (324, 'Asia/Ujung_Pandang', 'Ujung Pandang', 'Ujung Pandang.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (325, 'Asia/Ulaanbaatar', 'Ulaanbaatar', 'Ulaanbaatar.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (326, 'Asia/Ulan_Bator', 'Ulan Bator', 'Ulan Bator.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (327, 'Asia/Urumqi', 'Urumqi', 'Urumqi.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (328, 'Asia/Ust-Nera', 'Ust-Nera', 'Ust-Nera.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (329, 'Asia/Vientiane', 'Vientiane', 'Vientiane.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (330, 'Asia/Vladivostok', 'Vladivostok', 'Vladivostok.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (331, 'Asia/Yakutsk', 'Yakutsk', 'Yakutsk.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (332, 'Asia/Yangon', 'Yangon', 'Yangon.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (333, 'Asia/Yekaterinburg', 'Yekaterinburg', 'Yekaterinburg.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (334, 'Asia/Yerevan', 'Yerevan', 'Yerevan.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (335, 'Atlantic/Azores', 'Azores', 'Azores.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (336, 'Atlantic/Bermuda', 'Bermuda', 'Bermuda.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (337, 'Atlantic/Canary', 'Canary', 'Canary.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (338, 'Atlantic/Cape_Verde', 'Cape Verde', 'Cape Verde.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (339, 'Atlantic/Faeroe', 'Faeroe', 'Faeroe.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (340, 'Atlantic/Faroe', 'Faroe', 'Faroe.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (341, 'Atlantic/Jan_Mayen', 'Jan Mayen', 'Jan Mayen.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (342, 'Atlantic/Madeira', 'Madeira', 'Madeira.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (343, 'Atlantic/Reykjavik', 'Reykjavik', 'Reykjavik.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (344, 'Atlantic/South_Georgia', 'South Georgia', 'South Georgia.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (345, 'Atlantic/St_Helena', 'St Helena', 'St Helena.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (346, 'Atlantic/Stanley', 'Stanley', 'Stanley.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (347, 'Australia/ACT', 'Act', 'Act.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (348, 'Australia/Adelaide', 'Adelaide', 'Adelaide.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (349, 'Australia/Brisbane', 'Brisbane', 'Brisbane.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (350, 'Australia/Broken_Hill', 'Broken Hill', 'Broken Hill.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (351, 'Australia/Canberra', 'Canberra', 'Canberra.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (352, 'Australia/Currie', 'Currie', 'Currie.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (353, 'Australia/Darwin', 'Darwin', 'Darwin.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (354, 'Australia/Eucla', 'Eucla', 'Eucla.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (355, 'Australia/Hobart', 'Hobart', 'Hobart.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (356, 'Australia/LHI', 'Lhi', 'Lhi.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (357, 'Australia/Lindeman', 'Lindeman', 'Lindeman.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (358, 'Australia/Lord_Howe', 'Lord Howe', 'Lord Howe.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (359, 'Australia/Melbourne', 'Melbourne', 'Melbourne.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (360, 'Australia/NSW', 'Nsw', 'Nsw.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (361, 'Australia/North', 'North', 'North.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (362, 'Australia/Perth', 'Perth', 'Perth.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (363, 'Australia/Queensland', 'Queensland', 'Queensland.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (364, 'Australia/South', 'South', 'South.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (365, 'Australia/Sydney', 'Sydney', 'Sydney.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (366, 'Australia/Tasmania', 'Tasmania', 'Tasmania.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (367, 'Australia/Victoria', 'Victoria', 'Victoria.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (368, 'Australia/West', 'West', 'West.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (369, 'Australia/Yancowinna', 'Yancowinna', 'Yancowinna.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (370, 'Brazil/Acre', 'Acre', 'Acre.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (371, 'Brazil/DeNoronha', 'Denoronha', 'Denoronha.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (372, 'Brazil/East', 'East', 'East.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (373, 'Brazil/West', 'West', 'West.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (374, 'CET', 'Cet', 'Cet.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (375, 'CST6CDT', 'Cst6Cdt', 'Cst6Cdt.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (376, 'Canada/Atlantic', 'Atlantic', 'Atlantic.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (377, 'Canada/Central', 'Central', 'Central.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (378, 'Canada/Eastern', 'Eastern', 'Eastern.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (379, 'Canada/Mountain', 'Mountain', 'Mountain.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (380, 'Canada/Newfoundland', 'Newfoundland', 'Newfoundland.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (381, 'Canada/Pacific', 'Pacific', 'Pacific.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (382, 'Canada/Saskatchewan', 'Saskatchewan', 'Saskatchewan.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (383, 'Canada/Yukon', 'Yukon', 'Yukon.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (384, 'Chile/Continental', 'Continental', 'Continental.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (385, 'Chile/EasterIsland', 'Easterisland', 'Easterisland.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (386, 'Cuba', 'Cuba', 'Cuba.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (387, 'EET', 'Eet', 'Eet.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (388, 'EST', 'Est', 'Est.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (389, 'EST5EDT', 'Est5Edt', 'Est5Edt.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (390, 'Egypt', 'Egypt', 'Egypt.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (391, 'Eire', 'Eire', 'Eire.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (392, 'Etc/GMT', 'Gmt', 'Gmt.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (393, 'Etc/GMT+0', 'Gmt+0', 'Gmt+0.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (394, 'Etc/GMT+1', 'Gmt+1', 'Gmt+1.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (395, 'Etc/GMT+10', 'Gmt+10', 'Gmt+10.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (396, 'Etc/GMT+11', 'Gmt+11', 'Gmt+11.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (397, 'Etc/GMT+12', 'Gmt+12', 'Gmt+12.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (398, 'Etc/GMT+2', 'Gmt+2', 'Gmt+2.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (399, 'Etc/GMT+3', 'Gmt+3', 'Gmt+3.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (400, 'Etc/GMT+4', 'Gmt+4', 'Gmt+4.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (401, 'Etc/GMT+5', 'Gmt+5', 'Gmt+5.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (402, 'Etc/GMT+6', 'Gmt+6', 'Gmt+6.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (403, 'Etc/GMT+7', 'Gmt+7', 'Gmt+7.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (404, 'Etc/GMT+8', 'Gmt+8', 'Gmt+8.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (405, 'Etc/GMT+9', 'Gmt+9', 'Gmt+9.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (406, 'Etc/GMT-0', 'Gmt-0', 'Gmt-0.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (407, 'Etc/GMT-1', 'Gmt-1', 'Gmt-1.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (408, 'Etc/GMT-10', 'Gmt-10', 'Gmt-10.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (409, 'Etc/GMT-11', 'Gmt-11', 'Gmt-11.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (410, 'Etc/GMT-12', 'Gmt-12', 'Gmt-12.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (411, 'Etc/GMT-13', 'Gmt-13', 'Gmt-13.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (412, 'Etc/GMT-14', 'Gmt-14', 'Gmt-14.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (413, 'Etc/GMT-2', 'Gmt-2', 'Gmt-2.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (414, 'Etc/GMT-3', 'Gmt-3', 'Gmt-3.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (415, 'Etc/GMT-4', 'Gmt-4', 'Gmt-4.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (416, 'Etc/GMT-5', 'Gmt-5', 'Gmt-5.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (417, 'Etc/GMT-6', 'Gmt-6', 'Gmt-6.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (418, 'Etc/GMT-7', 'Gmt-7', 'Gmt-7.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (419, 'Etc/GMT-8', 'Gmt-8', 'Gmt-8.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (420, 'Etc/GMT-9', 'Gmt-9', 'Gmt-9.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (421, 'Etc/GMT0', 'Gmt0', 'Gmt0.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (422, 'Etc/Greenwich', 'Greenwich', 'Greenwich.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (423, 'Etc/UCT', 'Uct', 'Uct.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (424, 'Etc/UTC', 'Utc', 'Utc.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (425, 'Etc/Universal', 'Universal', 'Universal.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (426, 'Etc/Zulu', 'Zulu', 'Zulu.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (427, 'Europe/Amsterdam', 'Amsterdam', 'Amsterdam.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (428, 'Europe/Andorra', 'Andorra', 'Andorra.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (429, 'Europe/Astrakhan', 'Astrakhan', 'Astrakhan.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (430, 'Europe/Athens', 'Athens', 'Athens.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (431, 'Europe/Belfast', 'Belfast', 'Belfast.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (432, 'Europe/Belgrade', 'Belgrade', 'Belgrade.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (433, 'Europe/Berlin', 'Berlin', 'Berlin.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (434, 'Europe/Bratislava', 'Bratislava', 'Bratislava.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (435, 'Europe/Brussels', 'Brussels', 'Brussels.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (436, 'Europe/Bucharest', 'Bucharest', 'Bucharest.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (437, 'Europe/Budapest', 'Budapest', 'Budapest.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (438, 'Europe/Busingen', 'Busingen', 'Busingen.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (439, 'Europe/Chisinau', 'Chisinau', 'Chisinau.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (440, 'Europe/Copenhagen', 'Copenhagen', 'Copenhagen.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (441, 'Europe/Dublin', 'Dublin', 'Dublin.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (442, 'Europe/Gibraltar', 'Gibraltar', 'Gibraltar.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (443, 'Europe/Guernsey', 'Guernsey', 'Guernsey.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (444, 'Europe/Helsinki', 'Helsinki', 'Helsinki.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (445, 'Europe/Isle_of_Man', 'Isle Of Man', 'Isle Of Man.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (446, 'Europe/Istanbul', 'Istanbul', 'Istanbul.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (447, 'Europe/Jersey', 'Jersey', 'Jersey.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (448, 'Europe/Kaliningrad', 'Kaliningrad', 'Kaliningrad.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (449, 'Europe/Kiev', 'Kiev', 'Kiev.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (450, 'Europe/Kirov', 'Kirov', 'Kirov.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (451, 'Europe/Kyiv', 'Kyiv', 'Kyiv.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (452, 'Europe/Lisbon', 'Lisbon', 'Lisbon.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (453, 'Europe/Ljubljana', 'Ljubljana', 'Ljubljana.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (454, 'Europe/London', 'London', 'London.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (455, 'Europe/Luxembourg', 'Luxembourg', 'Luxembourg.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (456, 'Europe/Madrid', 'Madrid', 'Madrid.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (457, 'Europe/Malta', 'Malta', 'Malta.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (458, 'Europe/Mariehamn', 'Mariehamn', 'Mariehamn.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (459, 'Europe/Minsk', 'Minsk', 'Minsk.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (460, 'Europe/Monaco', 'Monaco', 'Monaco.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (461, 'Europe/Moscow', 'Moscow', 'Moscow.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (462, 'Europe/Nicosia', 'Nicosia', 'Nicosia.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (463, 'Europe/Oslo', 'Oslo', 'Oslo.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (464, 'Europe/Paris', 'Paris', 'Paris.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (465, 'Europe/Podgorica', 'Podgorica', 'Podgorica.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (466, 'Europe/Prague', 'Prague', 'Prague.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (467, 'Europe/Riga', 'Riga', 'Riga.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (468, 'Europe/Rome', 'Rome', 'Rome.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (469, 'Europe/Samara', 'Samara', 'Samara.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (470, 'Europe/San_Marino', 'San Marino', 'San Marino.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (471, 'Europe/Sarajevo', 'Sarajevo', 'Sarajevo.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (472, 'Europe/Saratov', 'Saratov', 'Saratov.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (473, 'Europe/Simferopol', 'Simferopol', 'Simferopol.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (474, 'Europe/Skopje', 'Skopje', 'Skopje.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (475, 'Europe/Sofia', 'Sofia', 'Sofia.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (476, 'Europe/Stockholm', 'Stockholm', 'Stockholm.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (477, 'Europe/Tallinn', 'Tallinn', 'Tallinn.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (478, 'Europe/Tirane', 'Tirane', 'Tirane.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (479, 'Europe/Tiraspol', 'Tiraspol', 'Tiraspol.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (480, 'Europe/Ulyanovsk', 'Ulyanovsk', 'Ulyanovsk.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (481, 'Europe/Uzhgorod', 'Uzhgorod', 'Uzhgorod.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (482, 'Europe/Vaduz', 'Vaduz', 'Vaduz.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (483, 'Europe/Vatican', 'Vatican', 'Vatican.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (484, 'Europe/Vienna', 'Vienna', 'Vienna.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (485, 'Europe/Vilnius', 'Vilnius', 'Vilnius.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (486, 'Europe/Volgograd', 'Volgograd', 'Volgograd.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (487, 'Europe/Warsaw', 'Warsaw', 'Warsaw.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (488, 'Europe/Zagreb', 'Zagreb', 'Zagreb.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (489, 'Europe/Zaporozhye', 'Zaporozhye', 'Zaporozhye.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (490, 'Europe/Zurich', 'Zurich', 'Zurich.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (491, 'Factory', 'Factory', 'Factory.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (492, 'GB', 'Gb', 'Gb.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (493, 'GB-Eire', 'Gb-Eire', 'Gb-Eire.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (494, 'GMT', 'Gmt', 'Gmt.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (495, 'GMT+0', 'Gmt+0', 'Gmt+0.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (496, 'GMT-0', 'Gmt-0', 'Gmt-0.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (497, 'GMT0', 'Gmt0', 'Gmt0.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (498, 'Greenwich', 'Greenwich', 'Greenwich.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (499, 'HST', 'Hst', 'Hst.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (500, 'Hongkong', 'Hongkong', 'Hongkong.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (501, 'Iceland', 'Iceland', 'Iceland.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (502, 'Indian/Antananarivo', 'Antananarivo', 'Antananarivo.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (503, 'Indian/Chagos', 'Chagos', 'Chagos.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (504, 'Indian/Christmas', 'Christmas', 'Christmas.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (505, 'Indian/Cocos', 'Cocos', 'Cocos.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (506, 'Indian/Comoro', 'Comoro', 'Comoro.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (507, 'Indian/Kerguelen', 'Kerguelen', 'Kerguelen.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (508, 'Indian/Mahe', 'Mahe', 'Mahe.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (509, 'Indian/Maldives', 'Maldives', 'Maldives.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (510, 'Indian/Mauritius', 'Mauritius', 'Mauritius.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (511, 'Indian/Mayotte', 'Mayotte', 'Mayotte.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (512, 'Indian/Reunion', 'Reunion', 'Reunion.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (513, 'Iran', 'Iran', 'Iran.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (514, 'Israel', 'Israel', 'Israel.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (515, 'Jamaica', 'Jamaica', 'Jamaica.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (516, 'Japan', 'Japan', 'Japan.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (517, 'Kwajalein', 'Kwajalein', 'Kwajalein.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (518, 'Libya', 'Libya', 'Libya.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (519, 'MET', 'Met', 'Met.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (520, 'MST', 'Mst', 'Mst.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (521, 'MST7MDT', 'Mst7Mdt', 'Mst7Mdt.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (522, 'Mexico/BajaNorte', 'Bajanorte', 'Bajanorte.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (523, 'Mexico/BajaSur', 'Bajasur', 'Bajasur.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (524, 'Mexico/General', 'General', 'General.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (525, 'NZ', 'Nz', 'Nz.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (526, 'NZ-CHAT', 'Nz-Chat', 'Nz-Chat.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (527, 'Navajo', 'Navajo', 'Navajo.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (528, 'PRC', 'Prc', 'Prc.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (529, 'PST8PDT', 'Pst8Pdt', 'Pst8Pdt.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (530, 'Pacific/Apia', 'Apia', 'Apia.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (531, 'Pacific/Auckland', 'Auckland', 'Auckland.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (532, 'Pacific/Bougainville', 'Bougainville', 'Bougainville.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (533, 'Pacific/Chatham', 'Chatham', 'Chatham.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (534, 'Pacific/Chuuk', 'Chuuk', 'Chuuk.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (535, 'Pacific/Easter', 'Easter', 'Easter.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (536, 'Pacific/Efate', 'Efate', 'Efate.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (537, 'Pacific/Enderbury', 'Enderbury', 'Enderbury.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (538, 'Pacific/Fakaofo', 'Fakaofo', 'Fakaofo.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (539, 'Pacific/Fiji', 'Fiji', 'Fiji.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (540, 'Pacific/Funafuti', 'Funafuti', 'Funafuti.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (541, 'Pacific/Galapagos', 'Galapagos', 'Galapagos.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (542, 'Pacific/Gambier', 'Gambier', 'Gambier.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (543, 'Pacific/Guadalcanal', 'Guadalcanal', 'Guadalcanal.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (544, 'Pacific/Guam', 'Guam', 'Guam.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (545, 'Pacific/Honolulu', 'Honolulu', 'Honolulu.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (546, 'Pacific/Johnston', 'Johnston', 'Johnston.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (547, 'Pacific/Kanton', 'Kanton', 'Kanton.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (548, 'Pacific/Kiritimati', 'Kiritimati', 'Kiritimati.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (549, 'Pacific/Kosrae', 'Kosrae', 'Kosrae.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (550, 'Pacific/Kwajalein', 'Kwajalein', 'Kwajalein.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (551, 'Pacific/Majuro', 'Majuro', 'Majuro.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (552, 'Pacific/Marquesas', 'Marquesas', 'Marquesas.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (553, 'Pacific/Midway', 'Midway', 'Midway.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (554, 'Pacific/Nauru', 'Nauru', 'Nauru.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (555, 'Pacific/Niue', 'Niue', 'Niue.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (556, 'Pacific/Norfolk', 'Norfolk', 'Norfolk.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (557, 'Pacific/Noumea', 'Noumea', 'Noumea.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (558, 'Pacific/Pago_Pago', 'Pago Pago', 'Pago Pago.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (559, 'Pacific/Palau', 'Palau', 'Palau.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (560, 'Pacific/Pitcairn', 'Pitcairn', 'Pitcairn.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (561, 'Pacific/Pohnpei', 'Pohnpei', 'Pohnpei.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (562, 'Pacific/Ponape', 'Ponape', 'Ponape.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (563, 'Pacific/Port_Moresby', 'Port Moresby', 'Port Moresby.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (564, 'Pacific/Rarotonga', 'Rarotonga', 'Rarotonga.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (565, 'Pacific/Saipan', 'Saipan', 'Saipan.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (566, 'Pacific/Samoa', 'Samoa', 'Samoa.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (567, 'Pacific/Tahiti', 'Tahiti', 'Tahiti.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (568, 'Pacific/Tarawa', 'Tarawa', 'Tarawa.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (569, 'Pacific/Tongatapu', 'Tongatapu', 'Tongatapu.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (570, 'Pacific/Truk', 'Truk', 'Truk.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (571, 'Pacific/Wake', 'Wake', 'Wake.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (572, 'Pacific/Wallis', 'Wallis', 'Wallis.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (573, 'Pacific/Yap', 'Yap', 'Yap.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (574, 'Poland', 'Poland', 'Poland.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (575, 'Portugal', 'Portugal', 'Portugal.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (576, 'ROC', 'Roc', 'Roc.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (577, 'ROK', 'Rok', 'Rok.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (578, 'Singapore', 'Singapore', 'Singapore.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (579, 'Turkey', 'Turkey', 'Turkey.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (580, 'UCT', 'Uct', 'Uct.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (581, 'US/Alaska', 'Alaska', 'Alaska.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (582, 'US/Aleutian', 'Aleutian', 'Aleutian.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (583, 'US/Arizona', 'Arizona', 'Arizona.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (584, 'US/Central', 'Central', 'Central.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (585, 'US/East-Indiana', 'East-Indiana', 'East-Indiana.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (586, 'US/Eastern', 'Eastern', 'Eastern.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (587, 'US/Hawaii', 'Hawaii', 'Hawaii.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (588, 'US/Indiana-Starke', 'Indiana-Starke', 'Indiana-Starke.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (589, 'US/Michigan', 'Michigan', 'Michigan.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (590, 'US/Mountain', 'Mountain', 'Mountain.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (591, 'US/Pacific', 'Pacific', 'Pacific.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (592, 'US/Samoa', 'Samoa', 'Samoa.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (593, 'UTC', 'Utc', 'Utc.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (594, 'Universal', 'Universal', 'Universal.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (595, 'W-SU', 'W-Su', 'W-Su.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (596, 'WET', 'Wet', 'Wet.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (597, 'Zulu', 'Zulu', 'Zulu.jpg');
INSERT INTO zeitzonen (id, zeitzone, stadt, cover) VALUES (598, 'localtime', 'Localtime', 'Localtime.jpg');